"use client";

import { FormEvent, useEffect, useState } from "react";
import { BrainCircuitIcon, CheckIcon, GitPullRequestArrowIcon, ScaleIcon, SearchIcon, XIcon } from "lucide-react";
import { useRouter } from "next/navigation";

import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { apiFetch, ApiRequestError } from "@/lib/api";
import { getTokens, getWorkspaceId } from "@/lib/auth";
import type { AgentTeam, CapabilityProposal, ConsensusSession, Coworker, MemoryConflict, Tool } from "@/lib/types";

export default function EvolutionPage() {
  const router = useRouter();
  const [workspaceId, setWorkspaceId] = useState("");
  const [coworkers, setCoworkers] = useState<Coworker[]>([]); const [tools, setTools] = useState<Tool[]>([]);
  const [proposals, setProposals] = useState<CapabilityProposal[]>([]); const [conflicts, setConflicts] = useState<MemoryConflict[]>([]);
  const [teams, setTeams] = useState<AgentTeam[]>([]); const [sessions, setSessions] = useState<ConsensusSession[]>([]);
  const [coworkerId, setCoworkerId] = useState(""); const [toolId, setToolId] = useState(""); const [rationale, setRationale] = useState("");
  const [teamId, setTeamId] = useState(""); const [question, setQuestion] = useState(""); const [options, setOptions] = useState("Proceed\nPause"); const [method, setMethod] = useState<ConsensusSession["method"]>("majority");
  const [mergedContent, setMergedContent] = useState<Record<string, string>>({});
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);

  async function load(id: string, scan = false) {
    const [coworkerRows, toolRows, proposalRows, conflictRows, teamRows] = await Promise.all([
      apiFetch<Coworker[]>(`/workspaces/${id}/coworkers`), apiFetch<Tool[]>("/tools"),
      apiFetch<CapabilityProposal[]>(`/workspaces/${id}/capability-proposals`),
      apiFetch<MemoryConflict[]>(`/workspaces/${id}/memory-conflicts${scan ? "?scan=true" : ""}`),
      apiFetch<AgentTeam[]>(`/agent-teams?workspace_id=${id}`),
    ]);
    setCoworkers(coworkerRows); setTools(toolRows); setProposals(proposalRows); setConflicts(conflictRows); setTeams(teamRows);
    setCoworkerId((value) => value || coworkerRows[0]?.id || ""); setToolId((value) => value || toolRows[0]?.id || ""); setTeamId((value) => value || teamRows[0]?.id || "");
    const sessionRows = (await Promise.all(teamRows.map((team) => apiFetch<ConsensusSession[]>(`/agent-teams/${team.id}/consensus`)))).flat(); setSessions(sessionRows);
  }
  useEffect(() => { if (!getTokens()) { router.push("/login"); return; } void getWorkspaceId().then((id) => { if (id) { setWorkspaceId(id); load(id).catch(() => setError("Couldn’t load adaptive collaboration data.")); } }); }, [router]);

  async function propose(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await apiFetch(`/workspaces/${workspaceId}/capability-proposals`, { method: "POST", body: JSON.stringify({ coworker_id: coworkerId, target_type: "tool", target_id: toolId, rationale, proposed_by_type: "coworker" }) }); setRationale(""); await load(workspaceId); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t create the proposal."); } finally { setBusy(false); } }
  async function decide(id: string, decision: "approve" | "deny") { setBusy(true); setError(null); try { await apiFetch(`/capability-proposals/${id}/decision`, { method: "POST", body: JSON.stringify({ decision }) }); await load(workspaceId); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t review the proposal."); } finally { setBusy(false); } }
  async function resolve(id: string, strategy: "keep_left" | "keep_right") { setBusy(true); setError(null); try { await apiFetch(`/memory-conflicts/${id}/resolve`, { method: "POST", body: JSON.stringify({ strategy }) }); await load(workspaceId); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t resolve the conflict."); } finally { setBusy(false); } }
  async function merge(id: string) { const content = mergedContent[id]?.trim(); if (!content) return; setBusy(true); setError(null); try { await apiFetch(`/memory-conflicts/${id}/resolve`, { method: "POST", body: JSON.stringify({ strategy: "merge", merged_content: content }) }); setMergedContent((current) => ({ ...current, [id]: "" })); await load(workspaceId); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t merge the conflict."); } finally { setBusy(false); } }
  async function startConsensus(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { const choices = options.split("\n").map((item) => item.trim()).filter(Boolean); await apiFetch(`/agent-teams/${teamId}/consensus`, { method: "POST", body: JSON.stringify({ question, options: choices, method }) }); setQuestion(""); await load(workspaceId); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t start consensus."); } finally { setBusy(false); } }

  return <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-6 px-4 py-10">
    <header><h1 className="flex items-center gap-2 text-2xl font-semibold"><BrainCircuitIcon className="size-6" />Adaptive collaboration</h1><p className="max-w-3xl text-sm text-muted-foreground">Review capability gaps, reconcile conflicting coworker memory, and ask teams to reach an auditable decision.</p></header>
    {error && <Alert variant="destructive" role="alert"><AlertDescription>{error}</AlertDescription></Alert>}
    <section className="grid gap-6 lg:grid-cols-2" aria-label="Capability and memory controls">
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><GitPullRequestArrowIcon className="size-4" />Capability proposals</CardTitle></CardHeader><CardContent className="grid gap-4"><form onSubmit={propose} className="grid gap-3"><div className="grid gap-1.5"><Label htmlFor="proposal-coworker">Coworker</Label><Select value={coworkerId} onValueChange={setCoworkerId}><SelectTrigger id="proposal-coworker"><SelectValue placeholder="Choose coworker" /></SelectTrigger><SelectContent>{coworkers.map((row) => <SelectItem key={row.id} value={row.id}>{row.name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-1.5"><Label htmlFor="proposal-tool">Requested tool</Label><Select value={toolId} onValueChange={setToolId}><SelectTrigger id="proposal-tool"><SelectValue placeholder="Choose tool" /></SelectTrigger><SelectContent>{tools.map((row) => <SelectItem key={row.id} value={row.id}>{row.name} · {row.risk_classification}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-1.5"><Label htmlFor="proposal-reason">Why is it needed?</Label><Textarea id="proposal-reason" value={rationale} onChange={(event) => setRationale(event.target.value)} placeholder="This task needs…" /><p className="text-xs text-muted-foreground">Submitting creates a request only. No tool is attached until an Owner/Admin approves.</p></div><Button className="w-fit" disabled={busy || !coworkerId || !toolId || !rationale.trim()}>Submit proposal</Button></form><div className="grid gap-2">{proposals.length === 0 ? <p className="py-5 text-center text-sm text-muted-foreground">No capability proposals yet.</p> : proposals.map((row) => <div key={row.id} className="grid gap-2 rounded-md border p-3"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-medium">{row.coworker_name} requests {row.target_name}</p><p className="text-sm text-muted-foreground">{row.rationale}</p></div><Badge variant={row.status === "denied" ? "destructive" : "outline"}>{row.status}</Badge></div>{row.status === "pending" && <div className="flex gap-2"><Button size="sm" onClick={() => decide(row.id, "approve")} disabled={busy}><CheckIcon data-icon="inline-start" />Approve</Button><Button size="sm" variant="outline" onClick={() => decide(row.id, "deny")} disabled={busy}><XIcon data-icon="inline-start" />Deny</Button></div>}</div>)}</div></CardContent></Card>
      <Card><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle className="flex items-center gap-2"><ScaleIcon className="size-4" />Memory conflicts</CardTitle><Button size="sm" variant="outline" onClick={() => load(workspaceId, true)} disabled={busy}><SearchIcon data-icon="inline-start" />Scan</Button></div></CardHeader><CardContent className="grid gap-3">{conflicts.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">No explicit subject:value conflicts found across coworker memories.</p> : conflicts.map((row) => <div key={row.id} className="grid gap-3 rounded-md border p-3"><div className="flex items-center justify-between gap-2"><p className="font-medium capitalize">{row.subject}</p><Badge variant="outline">{row.status}</Badge></div><div className="grid gap-2 sm:grid-cols-2"><div className="rounded bg-muted p-3 text-sm">{row.left_content}</div><div className="rounded bg-muted p-3 text-sm">{row.right_content}</div></div>{row.status === "open" && <><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => resolve(row.id, "keep_left")} disabled={busy}>Keep first</Button><Button size="sm" variant="outline" onClick={() => resolve(row.id, "keep_right")} disabled={busy}>Keep second</Button></div><div className="grid gap-1.5"><Label htmlFor={`merge-${row.id}`}>Or write a merged fact</Label><Textarea id={`merge-${row.id}`} value={mergedContent[row.id] || ""} onChange={(event) => setMergedContent((current) => ({ ...current, [row.id]: event.target.value }))} placeholder="The reconciled fact…" /><Button size="sm" className="w-fit" onClick={() => merge(row.id)} disabled={busy || !mergedContent[row.id]?.trim()}>Save merged memory</Button></div></>}</div>)}</CardContent></Card>
    </section>
    <Card><CardHeader><CardTitle>Team consensus</CardTitle></CardHeader><CardContent className="grid gap-5"><form onSubmit={startConsensus} className="grid gap-3 md:grid-cols-3"><div className="grid gap-1.5"><Label htmlFor="consensus-team">Agent team</Label><Select value={teamId} onValueChange={setTeamId}><SelectTrigger id="consensus-team"><SelectValue placeholder="Choose team" /></SelectTrigger><SelectContent>{teams.map((row) => <SelectItem key={row.id} value={row.id}>{row.name}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-1.5 md:col-span-2"><Label htmlFor="consensus-question">Decision question</Label><Input id="consensus-question" value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="Should we ship this release?" /></div><div className="grid gap-1.5 md:col-span-2"><Label htmlFor="consensus-options">Options (one per line)</Label><Textarea id="consensus-options" value={options} onChange={(event) => setOptions(event.target.value)} /></div><div className="grid gap-1.5"><Label htmlFor="consensus-method">Decision rule</Label><Select value={method} onValueChange={(value) => setMethod(value as ConsensusSession["method"])}><SelectTrigger id="consensus-method"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="majority">Majority</SelectItem><SelectItem value="unanimous">Unanimous</SelectItem><SelectItem value="confidence_weighted">Confidence weighted</SelectItem></SelectContent></Select></div><Button className="w-fit" disabled={busy || !teamId || !question.trim()}>Start consensus</Button></form><div className="grid gap-2">{sessions.map((row) => <div key={row.id} className="grid gap-2 rounded-md border p-3 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="font-medium">{row.question}</p><p className="text-sm text-muted-foreground">{row.agent_team_name} · {row.method.replaceAll("_", " ")} · {row.votes.length} vote(s)</p></div><Badge variant={row.status === "deadlocked" ? "destructive" : "outline"}>{row.result_option || row.status}</Badge></div>)}</div></CardContent></Card>
  </main>;
}
