"use client";

import { FormEvent, useEffect, useRef, useState } from "react";
import { MicIcon, MicOffIcon, SendIcon, Volume2Icon } from "lucide-react";
import { useRouter } from "next/navigation";

import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { apiFetch, ApiRequestError } from "@/lib/api";
import { getTokens, getWorkspaceId } from "@/lib/auth";
import type { Coworker, VoiceSession } from "@/lib/types";

type RecognitionResultEvent = { results: ArrayLike<{ isFinal: boolean; 0: { transcript: string } }>; resultIndex: number };
type Recognition = { continuous: boolean; interimResults: boolean; lang: string; start(): void; stop(): void; onresult: ((event: RecognitionResultEvent) => void) | null; onerror: (() => void) | null; onend: (() => void) | null };
type RecognitionConstructor = new () => Recognition;
type VoiceTurn = { id: string; user_transcript: string; assistant_transcript: string; status: "complete" | "needs_approval" | "failed"; approval_request_id: string | null; error_message: string };

export default function VoicePage() {
  const router = useRouter(); const recognitionRef = useRef<Recognition | null>(null); const listeningRef = useRef(false); const turnQueueRef = useRef<Promise<void>>(Promise.resolve());
  const [workspaceId, setWorkspaceId] = useState(""); const [coworkers, setCoworkers] = useState<Coworker[]>([]); const [coworkerId, setCoworkerId] = useState("");
  const [session, setSession] = useState<VoiceSession | null>(null); const [turns, setTurns] = useState<VoiceTurn[]>([]); const [draft, setDraft] = useState("");
  const [listening, setListening] = useState(false); const [busy, setBusy] = useState(false); const [supported, setSupported] = useState(true); const [error, setError] = useState<string | null>(null);

  useEffect(() => { if (!getTokens()) { router.push("/login"); return; } const host = window as typeof window & { SpeechRecognition?: RecognitionConstructor; webkitSpeechRecognition?: RecognitionConstructor }; void getWorkspaceId().then(async (id) => { setSupported(Boolean(host.SpeechRecognition || host.webkitSpeechRecognition)); if (!id) return; setWorkspaceId(id); try { const rows = await apiFetch<Coworker[]>(`/workspaces/${id}/coworkers`); setCoworkers(rows); setCoworkerId(rows[0]?.id || ""); } catch { setError("Couldn’t load coworkers."); } }); return () => { listeningRef.current = false; recognitionRef.current?.stop(); window.speechSynthesis?.cancel(); }; }, [router]);

  function speak(text: string) { if (!text || !("speechSynthesis" in window)) return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); utterance.lang = session?.language || "en-US"; window.speechSynthesis.speak(utterance); }
  async function sendTranscript(transcript: string, activeSession = session) { if (!activeSession || !transcript.trim()) return; setBusy(true); setError(null); try { const turn = await apiFetch<VoiceTurn>(`/voice-sessions/${activeSession.id}/turns`, { method: "POST", body: JSON.stringify({ transcript }) }); setTurns((current) => [...current, turn]); if (turn.assistant_transcript) speak(turn.assistant_transcript); if (turn.status === "needs_approval") setError("This turn is waiting for approval. Review it in Approvals, then continue in the linked conversation."); else if (turn.status === "failed") setError(turn.error_message || "The coworker couldn’t complete this turn."); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "The voice turn failed."); } finally { setBusy(false); } }
  async function begin() { if (!workspaceId || !coworkerId) return; setBusy(true); setError(null); try { const active = await apiFetch<VoiceSession>("/voice-sessions", { method: "POST", body: JSON.stringify({ workspace_id: workspaceId, coworker_id: coworkerId, language: "en-US" }) }); setSession(active); setTurns([]); if (supported) startListening(active); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t start voice mode."); } finally { setBusy(false); } }
  function startListening(activeSession = session) { if (!activeSession || listeningRef.current) return; const host = window as typeof window & { SpeechRecognition?: RecognitionConstructor; webkitSpeechRecognition?: RecognitionConstructor }; const Constructor = host.SpeechRecognition || host.webkitSpeechRecognition; if (!Constructor) { setSupported(false); return; } const recognition = new Constructor(); recognition.continuous = true; recognition.interimResults = false; recognition.lang = activeSession.language; recognition.onresult = (event) => { for (let index = event.resultIndex; index < event.results.length; index += 1) { const result = event.results[index]; if (result.isFinal) turnQueueRef.current = turnQueueRef.current.then(() => sendTranscript(result[0].transcript, activeSession)); } }; recognition.onerror = () => { setError("Microphone transcription stopped. Check browser microphone permission and try again."); listeningRef.current = false; setListening(false); }; recognition.onend = () => { if (listeningRef.current) { try { recognition.start(); } catch { listeningRef.current = false; setListening(false); } } }; recognitionRef.current = recognition; listeningRef.current = true; setListening(true); recognition.start(); }
  function stopListening() { listeningRef.current = false; recognitionRef.current?.stop(); recognitionRef.current = null; setListening(false); }
  async function end() { stopListening(); if (session) await apiFetch(`/voice-sessions/${session.id}`, { method: "PATCH", body: JSON.stringify({ status: "ended" }) }); setSession(null); }
  async function submit(event: FormEvent) { event.preventDefault(); const text = draft.trim(); if (!text) return; setDraft(""); await sendTranscript(text); }

  return <main className="mx-auto flex w-full max-w-4xl flex-1 flex-col gap-6 px-4 py-10"><header><h1 className="flex items-center gap-2 text-2xl font-semibold"><Volume2Icon className="size-6" />Live voice</h1><p className="max-w-2xl text-sm text-muted-foreground">Talk continuously with a coworker. Every transcript still follows normal model routing, tool approvals, memory, and audit controls.</p></header>{error && <Alert variant="destructive" role="alert"><AlertDescription>{error}</AlertDescription></Alert>}{!supported && <Alert><AlertDescription>Continuous speech recognition is unavailable in this browser. You can still use the typed transcript fallback below.</AlertDescription></Alert>}
    {!session ? <Card><CardHeader><CardTitle>Start a private voice session</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-[1fr_auto] sm:items-end"><div className="grid gap-1.5"><Label htmlFor="voice-coworker">Coworker</Label><Select value={coworkerId} onValueChange={setCoworkerId}><SelectTrigger id="voice-coworker"><SelectValue placeholder="Choose coworker" /></SelectTrigger><SelectContent>{coworkers.map((row) => <SelectItem key={row.id} value={row.id}>{row.name}</SelectItem>)}</SelectContent></Select></div><Button onClick={begin} disabled={busy || !coworkerId}><MicIcon data-icon="inline-start" />Start voice</Button></CardContent></Card> : <><Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-3"><div><CardTitle>Speaking with {session.coworker_name}</CardTitle><p className="text-sm text-muted-foreground">Session transcripts are private to you.</p></div><Badge variant={listening ? "default" : "outline"}>{listening ? "Listening" : "Paused"}</Badge></div></CardHeader><CardContent className="flex flex-wrap gap-2">{supported && (listening ? <Button variant="outline" onClick={stopListening}><MicOffIcon data-icon="inline-start" />Pause microphone</Button> : <Button onClick={() => startListening()}><MicIcon data-icon="inline-start" />Resume microphone</Button>)}<Button variant="outline" onClick={end}>End session</Button></CardContent></Card><section className="grid gap-3" aria-label="Voice transcript" aria-live="polite">{turns.length === 0 ? <Card><CardContent className="py-10 text-center text-sm text-muted-foreground">Start speaking, or type a transcript below.</CardContent></Card> : turns.map((turn) => <Card key={turn.id}><CardContent className="grid gap-3 py-4"><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">You</p><p>{turn.user_transcript}</p></div><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">{session.coworker_name}</p><p>{turn.assistant_transcript || turn.error_message || "Waiting for approval"}</p></div></CardContent></Card>)}</section><form onSubmit={submit} className="flex gap-2"><div className="grid flex-1 gap-1.5"><Label htmlFor="voice-fallback">Typed transcript</Label><Input id="voice-fallback" value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Type when a microphone is unavailable" disabled={busy} /></div><Button className="self-end" aria-label="Send typed transcript" disabled={busy || !draft.trim()}><SendIcon /></Button></form></>}
  </main>;
}
