"use client";

import { FormEvent, useEffect, useState } from "react";
import { Building2Icon, CopyIcon, KeyRoundIcon, PlusIcon, ShieldCheckIcon } from "lucide-react";
import { useRouter } from "next/navigation";

import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { apiFetch, ApiRequestError } from "@/lib/api";
import { getTokens, getWorkspaceId } from "@/lib/auth";
import type { EnterpriseSettings, SSOProvider } from "@/lib/types";

export default function EnterpriseSettingsPage() {
  const router = useRouter(); const [workspaceId, setWorkspaceId] = useState("");
  const [settings, setSettings] = useState<EnterpriseSettings | null>(null); const [providers, setProviders] = useState<SSOProvider[]>([]);
  const [protocol, setProtocol] = useState<"saml" | "oidc">("saml"); const [name, setName] = useState(""); const [issuer, setIssuer] = useState(""); const [ssoUrl, setSsoUrl] = useState(""); const [secret, setSecret] = useState("");
  const [scimToken, setScimToken] = useState(""); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  async function load(id: string) { const [enterprise, sso] = await Promise.all([apiFetch<EnterpriseSettings>(`/workspaces/${id}/enterprise`), apiFetch<SSOProvider[]>(`/workspaces/${id}/sso-providers`)]); setSettings(enterprise); setProviders(sso); }
  useEffect(() => { if (!getTokens()) { router.push("/login"); return; } void getWorkspaceId().then((id) => { if (id) { setWorkspaceId(id); load(id).catch(() => setError("Couldn’t load enterprise settings. Owner, admin, or security-admin access may be required.")); } }); }, [router]);
  async function saveSettings(next: Partial<EnterpriseSettings>) { if (!workspaceId) return; setBusy(true); setError(null); try { setSettings(await apiFetch<EnterpriseSettings>(`/workspaces/${workspaceId}/enterprise`, { method: "PATCH", body: JSON.stringify(next) })); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t save enterprise settings."); } finally { setBusy(false); } }
  async function addProvider(event: FormEvent) { event.preventDefault(); setBusy(true); setError(null); try { await apiFetch(`/workspaces/${workspaceId}/sso-providers`, { method: "POST", body: JSON.stringify({ protocol, name, issuer, sso_url: ssoUrl, entity_id: workspaceId, secret, email_domains: [], jit_provisioning: true }) }); setName(""); setIssuer(""); setSsoUrl(""); setSecret(""); await load(workspaceId); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t add SSO provider."); } finally { setBusy(false); } }
  async function createScimToken() { setBusy(true); try { const result = await apiFetch<{ token: string }>(`/workspaces/${workspaceId}/scim-tokens`, { method: "POST", body: JSON.stringify({ name: "Directory sync" }) }); setScimToken(result.token); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t create SCIM token."); } finally { setBusy(false); } }
  return <main className="mx-auto flex w-full max-w-5xl flex-1 flex-col gap-6 px-4 py-10"><header><h1 className="flex items-center gap-2 text-2xl font-semibold"><Building2Icon className="size-6" />Enterprise controls</h1><p className="max-w-3xl text-sm text-muted-foreground">Configure identity, directory provisioning, residency, retention, legal hold, and support commitments.</p></header>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
    {settings && <Card><CardHeader><CardTitle>Residency and service policy</CardTitle></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><div className="grid gap-1.5"><Label htmlFor="data-region">Data region</Label><Select value={settings.data_region} onValueChange={(value) => saveSettings({ data_region: value as EnterpriseSettings["data_region"] })}><SelectTrigger id="data-region"><SelectValue /></SelectTrigger><SelectContent>{["self_hosted", "us", "eu", "uk", "ca", "au"].map((region) => <SelectItem key={region} value={region}>{region.replace("_", " ").toUpperCase()}</SelectItem>)}</SelectContent></Select><p className="text-xs text-muted-foreground">Existing data must be migrated before this changes.</p></div><div className="grid gap-1.5"><Label htmlFor="retention">Retention days</Label><Input id="retention" type="number" min={1} max={3650} value={settings.retention_days} onChange={(e) => setSettings({ ...settings, retention_days: Number(e.target.value) })} onBlur={() => saveSettings({ retention_days: settings.retention_days })} /></div><div className="grid gap-1.5"><Label htmlFor="support-tier">Support tier</Label><Select value={settings.support_tier} onValueChange={(value) => saveSettings({ support_tier: value as EnterpriseSettings["support_tier"] })}><SelectTrigger id="support-tier"><SelectValue /></SelectTrigger><SelectContent>{["community", "standard", "premium", "dedicated"].map((tier) => <SelectItem key={tier} value={tier}>{tier}</SelectItem>)}</SelectContent></Select></div><div className="rounded-md border p-3"><p className="font-medium">Service target</p><p className="mt-1 text-2xl font-semibold tabular-nums">{settings.sla_uptime_percent}%</p><p className="text-xs text-muted-foreground">Response within {settings.sla_response_minutes} minutes</p><Button className="mt-3" variant={settings.legal_hold ? "default" : "outline"} onClick={() => saveSettings({ legal_hold: !settings.legal_hold })} disabled={busy}><ShieldCheckIcon data-icon="inline-start" />Legal hold {settings.legal_hold ? "on" : "off"}</Button></div></CardContent></Card>}
    <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Single sign-on</CardTitle></CardHeader><CardContent className="grid gap-4"><form onSubmit={addProvider} className="grid gap-3"><div className="grid gap-1.5"><Label htmlFor="sso-protocol">Protocol</Label><Select value={protocol} onValueChange={(value) => setProtocol(value as "saml" | "oidc")}><SelectTrigger id="sso-protocol"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="saml">SAML 2.0 broker</SelectItem><SelectItem value="oidc">OpenID Connect</SelectItem></SelectContent></Select></div><div className="grid gap-1.5"><Label htmlFor="sso-name">Provider name</Label><Input id="sso-name" required value={name} onChange={(e) => setName(e.target.value)} /></div><div className="grid gap-1.5"><Label htmlFor="sso-issuer">Issuer</Label><Input id="sso-issuer" required value={issuer} onChange={(e) => setIssuer(e.target.value)} /></div><div className="grid gap-1.5"><Label htmlFor="sso-url">Sign-in URL</Label><Input id="sso-url" type="url" required value={ssoUrl} onChange={(e) => setSsoUrl(e.target.value)} /></div><div className="grid gap-1.5"><Label htmlFor="sso-secret">Client or broker secret</Label><Input id="sso-secret" type="password" required value={secret} onChange={(e) => setSecret(e.target.value)} /></div><Button className="w-fit" disabled={busy}><PlusIcon data-icon="inline-start" />Add provider</Button></form><div className="grid gap-2">{providers.map((provider) => <div key={provider.id} className="flex items-center justify-between rounded-md border p-3"><span className="font-medium">{provider.name}</span><Badge variant="outline">{provider.protocol.toUpperCase()}</Badge></div>)}</div></CardContent></Card>
      <Card><CardHeader><CardTitle>Directory provisioning</CardTitle></CardHeader><CardContent className="grid gap-4"><p className="text-sm text-muted-foreground">Create a one-time SCIM bearer token for your identity provider. Provisioning endpoint: <code>/api/v1/scim/v2/Users</code>.</p>{scimToken ? <Alert><AlertDescription><strong>Copy this token now:</strong> <code className="break-all">{scimToken}</code><Button size="sm" variant="ghost" onClick={() => navigator.clipboard.writeText(scimToken)}><CopyIcon data-icon="inline-start" />Copy</Button></AlertDescription></Alert> : null}<Button className="w-fit" onClick={createScimToken} disabled={busy}><KeyRoundIcon data-icon="inline-start" />Create SCIM token</Button></CardContent></Card></div>
  </main>;
}
