# Generated by Django 6.0.7 on 2026-07-13 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_user_mfa_secret_providercredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('request_id', models.UUIDField()),
                ('coworker_id', models.UUIDField(blank=True, null=True)),
                ('deployment_mode', models.CharField(choices=[('deepseek_cloud', 'DeepSeek Cloud'), ('deepseek_self_hosted', 'DeepSeek Self-Hosted')], max_length=30)),
                ('model_id', models.CharField(max_length=100)),
                ('capability_requested', models.JSONField(blank=True, default=dict)),
                ('fallback_used', models.BooleanField(default=False)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('cost_usd', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('latency_ms', models.IntegerField()),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('rate_limited', 'Rate limited')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_calls', to='core.workspace')),
            ],
            options={
                'db_table': 'model_calls',
            },
        ),
    ]
