# Generated by Django 6.0.7 on 2026-07-13 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('core', '0005_approvalrequest_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcall',
            name='coworker_id',
        ),
        migrations.AddField(
            model_name='modelcall',
            name='coworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_calls', to='core.coworker'),
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='core.workspace')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('coworker', 'Coworker'), ('system', 'System')], max_length=20)),
                ('sender_id', models.UUIDField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
                ('tool_calls', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('streaming', 'Streaming'), ('needs_approval', 'Needs approval'), ('complete', 'Complete'), ('failed', 'Failed')], default='complete', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai.conversation')),
                ('parent_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regenerations', to='ai.message')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('participant_type', models.CharField(choices=[('user', 'User'), ('coworker', 'Coworker')], max_length=20)),
                ('participant_id', models.UUIDField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ai.conversation')),
            ],
            options={
                'db_table': 'conversation_participants',
                'constraints': [models.UniqueConstraint(fields=('conversation', 'participant_type', 'participant_id'), name='uniq_conversation_participant')],
            },
        ),
    ]
