# Generated by Django 6.0.7 on 2026-07-13 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_remove_modelcall_coworker_id_modelcall_coworker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tool_call_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
