"use client";

import { FormEvent, useEffect, useState } from "react";
import { AlertTriangleIcon, DownloadIcon, PlusIcon, ScanSearchIcon, ShieldIcon } from "lucide-react";
import { useRouter } from "next/navigation";

import { Alert, AlertDescription } from "@/components/ui/alert";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { apiFetch, ApiRequestError } from "@/lib/api";
import { getTokens, getWorkspaceId } from "@/lib/auth";
import type { AuditAnomaly, PolicyRule } from "@/lib/types";

export default function GovernancePage() {
  const router = useRouter(); const [workspaceId, setWorkspaceId] = useState(""); const [rules, setRules] = useState<PolicyRule[]>([]); const [anomalies, setAnomalies] = useState<AuditAnomaly[]>([]);
  const [name, setName] = useState(""); const [toolName, setToolName] = useState(""); const [effect, setEffect] = useState<PolicyRule["effect"]>("require_approval"); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [exportChecksum, setExportChecksum] = useState("");
  const [traces, setTraces] = useState<Array<{ id: string; coworker_name: string | null; explanation: string; latency_ms: number; created_at: string }>>([]);
  async function load(id: string, scan = false) { const [policyRows, anomalyRows, traceRows] = await Promise.all([apiFetch<PolicyRule[]>(`/workspaces/${id}/policy-rules`), apiFetch<AuditAnomaly[]>(`/workspaces/${id}/audit-anomalies${scan ? "?scan=true" : ""}`), apiFetch<Array<{ id: string; coworker_name: string | null; explanation: string; latency_ms: number; created_at: string }>>(`/workspaces/${id}/execution-traces`)]); setRules(policyRows); setAnomalies(anomalyRows); setTraces(traceRows); }
  useEffect(() => { if (!getTokens()) { router.push("/login"); return; } void getWorkspaceId().then((id) => { if (id) { setWorkspaceId(id); load(id).catch(() => setError("Couldn’t load governance data. Auditor or security-admin access may be required.")); } }); }, [router]);
  async function addRule(event: FormEvent) { event.preventDefault(); setBusy(true); try { await apiFetch(`/workspaces/${workspaceId}/policy-rules`, { method: "POST", body: JSON.stringify({ name, resource_type: "tool", action: "execute", conditions: toolName ? { tool_name: toolName } : {}, effect, priority: 100 }) }); setName(""); setToolName(""); await load(workspaceId); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t create policy rule."); } finally { setBusy(false); } }
  async function resolve(id: string) { setBusy(true); try { await apiFetch(`/workspaces/${workspaceId}/audit-anomalies`, { method: "PATCH", body: JSON.stringify({ id, status: "resolved" }) }); await load(workspaceId); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t resolve anomaly."); } finally { setBusy(false); } }
  async function exportEvidence() { setBusy(true); try { const row = await apiFetch<{ checksum: string; evidence: Record<string, unknown> }>(`/workspaces/${workspaceId}/compliance-exports`, { method: "POST", body: JSON.stringify({ export_type: "full" }) }); setExportChecksum(row.checksum); const blob = new Blob([JSON.stringify(row.evidence, null, 2)], { type: "application/json" }); const link = document.createElement("a"); link.href = URL.createObjectURL(blob); link.download = `agentarium-evidence-${row.checksum.slice(0, 8)}.json`; link.click(); URL.revokeObjectURL(link.href); } catch (err) { setError(err instanceof ApiRequestError ? err.message : "Couldn’t export compliance evidence."); } finally { setBusy(false); } }
  return <main className="mx-auto flex w-full max-w-6xl flex-1 flex-col gap-6 px-4 py-10"><header className="flex flex-wrap items-start justify-between gap-4"><div><h1 className="flex items-center gap-2 text-2xl font-semibold"><ShieldIcon className="size-6" />Governance</h1><p className="max-w-3xl text-sm text-muted-foreground">Apply fine-grained controls, investigate behavioral anomalies, and export integrity-checked compliance evidence.</p></div><Button onClick={exportEvidence} disabled={busy}><DownloadIcon data-icon="inline-start" />Export evidence</Button></header>{error && <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}{exportChecksum && <Alert><AlertDescription>Evidence exported. SHA-256: <code className="break-all">{exportChecksum}</code></AlertDescription></Alert>}
    <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Policy engine</CardTitle></CardHeader><CardContent className="grid gap-4"><form onSubmit={addRule} className="grid gap-3"><div className="grid gap-1.5"><Label htmlFor="rule-name">Rule name</Label><Input id="rule-name" value={name} onChange={(e) => setName(e.target.value)} required placeholder="Review external messages" /></div><div className="grid gap-1.5"><Label htmlFor="rule-tool">Tool name (optional)</Label><Input id="rule-tool" value={toolName} onChange={(e) => setToolName(e.target.value)} placeholder="send_email" /><p className="text-xs text-muted-foreground">Leave blank to apply to every tool execution.</p></div><div className="grid gap-1.5"><Label htmlFor="rule-effect">Effect</Label><Select value={effect} onValueChange={(value) => setEffect(value as PolicyRule["effect"])}><SelectTrigger id="rule-effect"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="require_approval">Require approval</SelectItem><SelectItem value="deny">Deny</SelectItem><SelectItem value="allow">Allow</SelectItem></SelectContent></Select></div><Button className="w-fit" disabled={busy || !name.trim()}><PlusIcon data-icon="inline-start" />Add rule</Button></form><div className="grid gap-2">{rules.map((rule) => <div className="flex items-center justify-between gap-3 rounded-md border p-3" key={rule.id}><div><p className="font-medium">{rule.name}</p><p className="text-xs text-muted-foreground">{rule.resource_type}:{rule.action} · priority {rule.priority}</p></div><Badge variant={rule.effect === "deny" ? "destructive" : "outline"}>{rule.effect.replace("_", " ")}</Badge></div>)}</div></CardContent></Card>
      <Card><CardHeader><div className="flex items-center justify-between gap-3"><CardTitle className="flex items-center gap-2"><ScanSearchIcon className="size-4" />Behavior anomalies</CardTitle><Button size="sm" variant="outline" onClick={() => load(workspaceId, true)} disabled={busy}>Scan now</Button></div></CardHeader><CardContent className="grid gap-3">{anomalies.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">No anomalies detected.</p> : anomalies.map((anomaly) => <div key={anomaly.id} className="grid gap-3 rounded-md border p-3"><div className="flex items-start justify-between gap-3"><div><p className="flex items-center gap-2 font-medium"><AlertTriangleIcon className="size-4" />{anomaly.summary}</p><p className="text-xs text-muted-foreground">{new Date(anomaly.detected_at).toLocaleString()}</p></div><Badge variant={anomaly.severity === "critical" || anomaly.severity === "high" ? "destructive" : "outline"}>{anomaly.severity} · {anomaly.status}</Badge></div>{anomaly.status !== "resolved" && <Button size="sm" variant="outline" className="w-fit" onClick={() => resolve(anomaly.id)}>Mark resolved</Button>}</div>)}</CardContent></Card></div>
    <Card><CardHeader><CardTitle>Explainability traces</CardTitle></CardHeader><CardContent className="grid gap-2">{traces.length === 0 ? <p className="py-8 text-center text-sm text-muted-foreground">No model execution traces yet.</p> : traces.slice(0, 20).map((trace) => <div key={trace.id} className="grid gap-1 rounded-md border p-3 sm:grid-cols-[1fr_auto] sm:items-center"><div><p className="text-sm">{trace.explanation}</p><p className="text-xs text-muted-foreground">{trace.coworker_name || "System"} · {new Date(trace.created_at).toLocaleString()}</p></div><Badge variant="outline">{trace.latency_ms} ms</Badge></div>)}</CardContent></Card>
  </main>;
}
