# Generated by Django 6.0.7 on 2026-07-20 12:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0006_modelcall_workspace_created_index'),
        ('core', '0029_alter_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDomainPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('trusted_domains', models.JSONField(blank=True, default=list)),
                ('blocked_domains', models.JSONField(blank=True, default=list)),
                ('default_controls', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='research_domain_policy', to='core.workspace')),
            ],
            options={
                'db_table': 'research_domain_policies',
            },
        ),
        migrations.CreateModel(
            name='ResearchRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('query', models.TextField()),
                ('mode', models.CharField(choices=[('deep', 'Deep research'), ('crawl', 'Website crawl'), ('extraction', 'Structured extraction')], default='deep', max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('planning', 'Planning'), ('searching', 'Searching'), ('reading', 'Reading'), ('comparing', 'Comparing'), ('writing', 'Writing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=20)),
                ('current_stage', models.CharField(default='queued', max_length=50)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('controls', models.JSONField(blank=True, default=dict)),
                ('plan', models.JSONField(blank=True, default=list)),
                ('report_markdown', models.TextField(blank=True)),
                ('weak_evidence', models.BooleanField(default=False)),
                ('weak_evidence_reasons', models.JSONField(blank=True, default=list)),
                ('conflicts', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coworker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_runs', to='core.coworker')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_runs', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_runs', to='core.workspace')),
            ],
            options={
                'db_table': 'research_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrawlPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('parent_url', models.TextField(blank=True)),
                ('depth', models.PositiveSmallIntegerField(default=0)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('robots_allowed', models.BooleanField(default=True)),
                ('from_cache', models.BooleanField(default=False)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_pages', to='research.researchrun')),
            ],
            options={
                'db_table': 'crawl_pages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('webpage', 'Webpage'), ('document', 'Document'), ('browser', 'JavaScript webpage'), ('search', 'Search result')], default='webpage', max_length=20)),
                ('requested_url', models.TextField()),
                ('url', models.TextField()),
                ('canonical_url', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=10)),
                ('content_type', models.CharField(blank=True, max_length=255)),
                ('checksum', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('trust_level', models.CharField(choices=[('trusted', 'Trusted'), ('standard', 'Standard'), ('blocked', 'Blocked')], default='standard', max_length=20)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates', to='research.researchsource')),
                ('run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='research.researchrun')),
            ],
            options={
                'db_table': 'research_sources',
                'ordering': ['accessed_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('claim', models.TextField(blank=True)),
                ('passage', models.TextField()),
                ('locator', models.CharField(blank=True, max_length=255)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('relevance', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='research.researchsource')),
            ],
            options={
                'db_table': 'research_evidence',
                'ordering': ['ordinal'],
            },
        ),
        migrations.CreateModel(
            name='ResearchStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('stage', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='research.researchrun')),
            ],
            options={
                'db_table': 'research_steps',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='StructuredExtraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('schema', models.JSONField()),
                ('data', models.JSONField(default=dict)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='research.researchrun')),
            ],
            options={
                'db_table': 'structured_extractions',
            },
        ),
        migrations.CreateModel(
            name='WebsiteMonitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField()),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('use_browser', models.BooleanField(default=False)),
                ('crawl_pages', models.PositiveSmallIntegerField(default=1)),
                ('max_depth', models.PositiveSmallIntegerField(default=0)),
                ('controls', models.JSONField(blank=True, default=dict)),
                ('next_run_at', models.DateTimeField()),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coworker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_monitors', to='core.coworker')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_monitors', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='website_monitors', to='core.workspace')),
            ],
            options={
                'db_table': 'website_monitors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('title', models.CharField(blank=True, max_length=500)),
                ('checksum', models.CharField(max_length=64)),
                ('text', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='research.websitemonitor')),
            ],
            options={
                'db_table': 'website_snapshots',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteMonitorRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('change_detected', models.BooleanField(default=False)),
                ('change_summary', models.TextField(blank=True)),
                ('diff', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='research.websitemonitor')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='research.websitesnapshot')),
            ],
            options={
                'db_table': 'website_monitor_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('ordinal', models.PositiveIntegerField()),
                ('claim', models.TextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='ai.message')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='message_citations', to='research.researchevidence')),
            ],
            options={
                'db_table': 'message_citations',
                'ordering': ['ordinal'],
                'constraints': [models.UniqueConstraint(fields=('message', 'ordinal'), name='uniq_message_citation_ordinal')],
            },
        ),
        migrations.AddIndex(
            model_name='researchrun',
            index=models.Index(fields=['workspace', 'status', 'created_at'], name='research_ru_workspa_e6a029_idx'),
        ),
        migrations.AddConstraint(
            model_name='crawlpage',
            constraint=models.UniqueConstraint(fields=('run', 'url'), name='uniq_research_crawl_url'),
        ),
        migrations.AddIndex(
            model_name='researchsource',
            index=models.Index(fields=['run', 'checksum'], name='research_so_run_id_b81c7d_idx'),
        ),
        migrations.AddConstraint(
            model_name='researchevidence',
            constraint=models.UniqueConstraint(fields=('source', 'ordinal'), name='uniq_source_evidence_ordinal'),
        ),
        migrations.AddConstraint(
            model_name='researchstep',
            constraint=models.UniqueConstraint(fields=('run', 'sequence'), name='uniq_research_step_sequence'),
        ),
        migrations.AddIndex(
            model_name='websitemonitor',
            index=models.Index(fields=['enabled', 'next_run_at'], name='website_mon_enabled_553cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='websitemonitor',
            index=models.Index(fields=['workspace', 'created_at'], name='website_mon_workspa_ec65b3_idx'),
        ),
        migrations.AddIndex(
            model_name='websitesnapshot',
            index=models.Index(fields=['monitor', 'captured_at'], name='website_sna_monitor_80d227_idx'),
        ),
    ]
