from django.urls import path
from rest_framework_simplejwt.views import TokenRefreshView

from core.chat_views import (
    ApprovalPolicyDeleteView,
    ApprovalPolicyListCreateView,
    ApprovalRequestApproveView,
    ApprovalRequestDenyView,
    ApprovalRequestListView,
    ApprovalRequestStatsView,
    ConversationDetailView,
    ConversationListCreateView,
    MessageListSendView,
    MessagePatchView,
    MessageRegenerateView,
    MessageStreamView,
)
from core.views import (
    CoworkerDetailView,
    CoworkerListCreateView,
    CoworkerToolAttachView,
    CoworkerToolDetachView,
    CoworkerVersionRollbackView,
    CoworkerVersionsView,
    GoogleOAuthCallbackView,
    LoginView,
    LogoutView,
    MeView,
    MFAEnrollConfirmView,
    MFAEnrollView,
    MFAVerifyView,
    ProviderCredentialDestroyView,
    ProviderCredentialListCreateView,
    RegisterView,
    ToolCatalogListView,
    WorkspaceDetailView,
    WorkspaceListView,
)
from core.memory_views import (
    CoworkerKnowledgeBaseAttachView,
    CoworkerKnowledgeBaseDetachView,
    KnowledgeBaseDetailView,
    KnowledgeBaseListCreateView,
    KnowledgeDocumentStatusView,
    KnowledgeDocumentUploadView,
    MemoryDetailView,
    MemoryListCreateView,
    MemoryTimelineView,
)
from core.task_views import (
    ConversationTaskHandoffView,
    CoworkerStatusListView,
    NotificationListView,
    NotificationReadView,
    TaskApproveView,
    TaskDenyView,
    TaskDetailView,
    TaskListCreateView,
)
from core.v2_views import (
    AgentTeamDetailView,
    AgentTeamListCreateView,
    AgentTeamRunDetailView,
    AgentTeamRunView,
    ApiTokenListCreateView,
    ApiTokenRevokeView,
    CoworkerSkillAttachView,
    HumanTeamListCreateView,
    IntegrationListCreateView,
    MarketplaceForkView,
    MarketplaceInstallView,
    MarketplaceListingDetailView,
    MarketplaceListingListCreateView,
    MarketplaceListingVersionCreateView,
    MarketplaceReviewListCreateView,
    OrganizationListCreateView,
    PolicyFloorListCreateView,
    ProjectDetailView,
    ProjectListCreateView,
    ProjectResourceCreateView,
    ProvisionTeamView,
    SubscriptionView,
    TeamSuggestionView,
    TeamTemplateListView,
    WebhookIngressView,
    WorkflowCheckpointApproveView,
    WorkflowCheckpointDenyView,
    WorkflowDetailView,
    WorkflowListCreateView,
    WorkflowRunCreateListView,
    WorkflowRunDetailView,
    WorkflowTriggerCreateView,
    WorkspaceMemberDetailView,
    WorkspaceMemberListCreateView,
)
from core.admin_views import AuditLogView, UsageView
from core.v3_views import (
    ArtifactListCreateView,
    AuditAnomalyListView,
    ComplianceExportListCreateView,
    CoworkerBundleExportView,
    CoworkerBundleImportView,
    EnterpriseSettingsView,
    ExecutionTraceListView,
    MarketplaceCheckoutView,
    MarketplacePaymentWebhookView,
    PayoutAccountView,
    PolicyRuleDetailView,
    PolicyRuleListCreateView,
    SCIMTokenListCreateView,
    SCIMUserDetailView,
    SCIMUsersView,
    SSOCallbackView,
    SSOLoginView,
    SSOProviderListCreateView,
)
from core.v4_views import (
    CapabilityProposalDecisionView,
    CapabilityProposalListCreateView,
    ConsensusSessionDetailView,
    ConsensusSessionListCreateView,
    MemoryConflictListCreateView,
    MemoryConflictResolveView,
    VoiceSessionDetailView,
    VoiceSessionListCreateView,
    VoiceTurnCreateView,
)

urlpatterns = [
    path("auth/register", RegisterView.as_view(), name="auth-register"),
    path("auth/login", LoginView.as_view(), name="auth-login"),
    path("auth/logout", LogoutView.as_view(), name="auth-logout"),
    path("auth/refresh", TokenRefreshView.as_view(), name="auth-refresh"),
    path(
        "auth/oauth/google/callback",
        GoogleOAuthCallbackView.as_view(),
        name="auth-oauth-google-callback",
    ),
    path("auth/mfa/enroll", MFAEnrollView.as_view(), name="auth-mfa-enroll"),
    path(
        "auth/mfa/enroll/confirm",
        MFAEnrollConfirmView.as_view(),
        name="auth-mfa-enroll-confirm",
    ),
    path("auth/mfa/verify", MFAVerifyView.as_view(), name="auth-mfa-verify"),
    path("me", MeView.as_view(), name="me"),
    path("workspaces", WorkspaceListView.as_view(), name="workspace-list"),
    path("organizations", OrganizationListCreateView.as_view(), name="organization-list-create"),
    path(
        "workspaces/<uuid:workspace_id>", WorkspaceDetailView.as_view(), name="workspace-detail"
    ),
    path(
        "workspaces/<uuid:workspace_id>/provider-credentials",
        ProviderCredentialListCreateView.as_view(),
        name="provider-credential-list-create",
    ),
    path("workspaces/<uuid:workspace_id>/members", WorkspaceMemberListCreateView.as_view(), name="workspace-member-list-create"),
    path("workspaces/<uuid:workspace_id>/members/<uuid:member_id>", WorkspaceMemberDetailView.as_view(), name="workspace-member-detail"),
    path("workspaces/<uuid:workspace_id>/policy-floors", PolicyFloorListCreateView.as_view(), name="policy-floor-list-create"),
    path("workspaces/<uuid:workspace_id>/api-tokens", ApiTokenListCreateView.as_view(), name="api-token-list-create"),
    path("workspaces/<uuid:workspace_id>/api-tokens/<uuid:token_id>", ApiTokenRevokeView.as_view(), name="api-token-revoke"),
    path("workspaces/<uuid:workspace_id>/subscription", SubscriptionView.as_view(), name="subscription-detail"),
    path(
        "workspaces/<uuid:workspace_id>/provider-credentials/<uuid:cred_id>",
        ProviderCredentialDestroyView.as_view(),
        name="provider-credential-destroy",
    ),
    path("tools", ToolCatalogListView.as_view(), name="tool-catalog-list"),
    path(
        "workspaces/<uuid:workspace_id>/coworkers",
        CoworkerListCreateView.as_view(),
        name="coworker-list-create",
    ),
    path(
        "workspaces/<uuid:workspace_id>/coworkers/status",
        CoworkerStatusListView.as_view(),
        name="coworker-status-list",
    ),
    path("coworkers/<uuid:coworker_id>", CoworkerDetailView.as_view(), name="coworker-detail"),
    path(
        "coworkers/<uuid:coworker_id>/versions",
        CoworkerVersionsView.as_view(),
        name="coworker-versions",
    ),
    path(
        "coworkers/<uuid:coworker_id>/versions/<int:version_number>/rollback",
        CoworkerVersionRollbackView.as_view(),
        name="coworker-version-rollback",
    ),
    path(
        "coworkers/<uuid:coworker_id>/tools",
        CoworkerToolAttachView.as_view(),
        name="coworker-tool-attach",
    ),
    path(
        "coworkers/<uuid:coworker_id>/tools/<uuid:tool_id>",
        CoworkerToolDetachView.as_view(),
        name="coworker-tool-detach",
    ),
    path("coworkers/<uuid:coworker_id>/skills", CoworkerSkillAttachView.as_view(), name="coworker-skill-attach"),
    path("coworkers/<uuid:coworker_id>/skills/<uuid:skill_id>", CoworkerSkillAttachView.as_view(), name="coworker-skill-detach"),
    path("conversations", ConversationListCreateView.as_view(), name="conversation-list-create"),
    path(
        "conversations/<uuid:conversation_id>",
        ConversationDetailView.as_view(),
        name="conversation-detail",
    ),
    path(
        "conversations/<uuid:conversation_id>/messages",
        MessageListSendView.as_view(),
        name="conversation-message-list-send",
    ),
    path(
        "conversations/<uuid:conversation_id>/messages/stream",
        MessageStreamView.as_view(),
        name="conversation-message-stream",
    ),
    path(
        "messages/<uuid:message_id>/regenerate",
        MessageRegenerateView.as_view(),
        name="message-regenerate",
    ),
    path("messages/<uuid:message_id>", MessagePatchView.as_view(), name="message-patch"),
    path(
        "workspaces/<uuid:workspace_id>/approval-requests",
        ApprovalRequestListView.as_view(),
        name="approval-request-list",
    ),
    path(
        "workspaces/<uuid:workspace_id>/approval-requests/stats",
        ApprovalRequestStatsView.as_view(),
        name="approval-request-stats",
    ),
    path(
        "workspaces/<uuid:workspace_id>/approval-policies",
        ApprovalPolicyListCreateView.as_view(),
        name="approval-policy-list-create",
    ),
    path(
        "approval-policies/<uuid:policy_id>",
        ApprovalPolicyDeleteView.as_view(),
        name="approval-policy-delete",
    ),
    path(
        "approval-requests/<uuid:approval_request_id>/approve",
        ApprovalRequestApproveView.as_view(),
        name="approval-request-approve",
    ),
    path(
        "approval-requests/<uuid:approval_request_id>/deny",
        ApprovalRequestDenyView.as_view(),
        name="approval-request-deny",
    ),
    path("memory", MemoryListCreateView.as_view(), name="memory-list-create"),
    path("memory/<uuid:memory_id>", MemoryDetailView.as_view(), name="memory-detail"),
    path(
        "memory/<str:scope>/<uuid:scope_id>/timeline",
        MemoryTimelineView.as_view(),
        name="memory-timeline",
    ),
    path("knowledge-bases", KnowledgeBaseListCreateView.as_view(), name="knowledge-base-list-create"),
    path("knowledge-bases/<uuid:kb_id>", KnowledgeBaseDetailView.as_view(), name="knowledge-base-detail"),
    path(
        "knowledge-bases/<uuid:kb_id>/documents",
        KnowledgeDocumentUploadView.as_view(),
        name="knowledge-document-upload",
    ),
    path(
        "knowledge-bases/<uuid:kb_id>/documents/<uuid:doc_id>/status",
        KnowledgeDocumentStatusView.as_view(),
        name="knowledge-document-status",
    ),
    path(
        "coworkers/<uuid:coworker_id>/knowledge-bases",
        CoworkerKnowledgeBaseAttachView.as_view(),
        name="coworker-knowledge-base-attach",
    ),
    path(
        "coworkers/<uuid:coworker_id>/knowledge-bases/<uuid:kb_id>",
        CoworkerKnowledgeBaseDetachView.as_view(),
        name="coworker-knowledge-base-detach",
    ),
    path("tasks", TaskListCreateView.as_view(), name="task-list-create"),
    path("tasks/<uuid:task_id>", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/<uuid:task_id>/approve", TaskApproveView.as_view(), name="task-approve"),
    path("tasks/<uuid:task_id>/deny", TaskDenyView.as_view(), name="task-deny"),
    path(
        "conversations/<uuid:conversation_id>/tasks",
        ConversationTaskHandoffView.as_view(),
        name="conversation-task-handoff",
    ),
    path("notifications", NotificationListView.as_view(), name="notification-list"),
    path(
        "notifications/<uuid:notification_id>/read",
        NotificationReadView.as_view(),
        name="notification-read",
    ),
    path(
        "workspaces/<uuid:workspace_id>/audit-log",
        AuditLogView.as_view(),
        name="workspace-audit-log",
    ),
    path(
        "workspaces/<uuid:workspace_id>/usage",
        UsageView.as_view(),
        name="workspace-usage",
    ),
    path("teams", HumanTeamListCreateView.as_view(), name="human-team-list-create"),
    path("team-templates", TeamTemplateListView.as_view(), name="team-template-list"),
    path("workspaces/<uuid:workspace_id>/provision-team", ProvisionTeamView.as_view(), name="provision-team"),
    path("workspaces/<uuid:workspace_id>/team-suggestions", TeamSuggestionView.as_view(), name="team-suggestions"),
    path("agent-teams", AgentTeamListCreateView.as_view(), name="agent-team-list-create"),
    path("agent-teams/<uuid:team_id>", AgentTeamDetailView.as_view(), name="agent-team-detail"),
    path("agent-teams/<uuid:team_id>/run", AgentTeamRunView.as_view(), name="agent-team-run"),
    path("agent-team-runs/<uuid:run_id>", AgentTeamRunDetailView.as_view(), name="agent-team-run-detail"),
    path("projects", ProjectListCreateView.as_view(), name="project-list-create"),
    path("projects/<uuid:project_id>", ProjectDetailView.as_view(), name="project-detail"),
    path("projects/<uuid:project_id>/resources", ProjectResourceCreateView.as_view(), name="project-resource-create"),
    path("workflows", WorkflowListCreateView.as_view(), name="workflow-list-create"),
    path("workflows/<uuid:workflow_id>", WorkflowDetailView.as_view(), name="workflow-detail"),
    path("workflows/<uuid:workflow_id>/triggers", WorkflowTriggerCreateView.as_view(), name="workflow-trigger-create"),
    path("workflows/<uuid:workflow_id>/runs", WorkflowRunCreateListView.as_view(), name="workflow-run-list-create"),
    path("workflow-runs/<uuid:run_id>", WorkflowRunDetailView.as_view(), name="workflow-run-detail"),
    path("workflow-runs/<uuid:run_id>/steps/<uuid:step_id>/approve", WorkflowCheckpointApproveView.as_view(), name="workflow-step-approve"),
    path("workflow-runs/<uuid:run_id>/steps/<uuid:step_id>/deny", WorkflowCheckpointDenyView.as_view(), name="workflow-step-deny"),
    path("marketplace/listings", MarketplaceListingListCreateView.as_view(), name="marketplace-listing-list-create"),
    path("marketplace/listings/<uuid:listing_id>", MarketplaceListingDetailView.as_view(), name="marketplace-listing-detail"),
    path("marketplace/listings/<uuid:listing_id>/versions", MarketplaceListingVersionCreateView.as_view(), name="marketplace-listing-version-create"),
    path("marketplace/listings/<uuid:listing_id>/install", MarketplaceInstallView.as_view(), name="marketplace-install"),
    path("marketplace/listings/<uuid:listing_id>/fork", MarketplaceForkView.as_view(), name="marketplace-fork"),
    path("marketplace/listings/<uuid:listing_id>/reviews", MarketplaceReviewListCreateView.as_view(), name="marketplace-review-list-create"),
    path("integrations", IntegrationListCreateView.as_view(), name="integration-list-create"),
    path("webhooks/<str:integration>/<str:workspace_token>", WebhookIngressView.as_view(), name="webhook-ingress"),
    path("workspaces/<uuid:workspace_id>/enterprise", EnterpriseSettingsView.as_view(), name="enterprise-settings"),
    path("workspaces/<uuid:workspace_id>/policy-rules", PolicyRuleListCreateView.as_view(), name="policy-rule-list-create"),
    path("workspaces/<uuid:workspace_id>/policy-rules/<uuid:rule_id>", PolicyRuleDetailView.as_view(), name="policy-rule-detail"),
    path("workspaces/<uuid:workspace_id>/sso-providers", SSOProviderListCreateView.as_view(), name="sso-provider-list-create"),
    path("sso/<uuid:provider_id>/login", SSOLoginView.as_view(), name="sso-login"),
    path("sso/<uuid:provider_id>/callback", SSOCallbackView.as_view(), name="sso-callback"),
    path("workspaces/<uuid:workspace_id>/scim-tokens", SCIMTokenListCreateView.as_view(), name="scim-token-list-create"),
    path("scim/v2/Users", SCIMUsersView.as_view(), name="scim-users"),
    path("scim/v2/Users/<uuid:user_id>", SCIMUserDetailView.as_view(), name="scim-user-detail"),
    path("workspaces/<uuid:workspace_id>/audit-anomalies", AuditAnomalyListView.as_view(), name="audit-anomaly-list"),
    path("workspaces/<uuid:workspace_id>/compliance-exports", ComplianceExportListCreateView.as_view(), name="compliance-export-list-create"),
    path("workspaces/<uuid:workspace_id>/execution-traces", ExecutionTraceListView.as_view(), name="execution-trace-list"),
    path("coworkers/<uuid:coworker_id>/export", CoworkerBundleExportView.as_view(), name="coworker-bundle-export"),
    path("workspaces/<uuid:workspace_id>/coworkers/import", CoworkerBundleImportView.as_view(), name="coworker-bundle-import"),
    path("artifacts", ArtifactListCreateView.as_view(), name="artifact-list-create"),
    path("marketplace/listings/<uuid:listing_id>/checkout", MarketplaceCheckoutView.as_view(), name="marketplace-checkout"),
    path("marketplace/payment-webhook", MarketplacePaymentWebhookView.as_view(), name="marketplace-payment-webhook"),
    path("workspaces/<uuid:workspace_id>/payout-account", PayoutAccountView.as_view(), name="payout-account"),
    path("workspaces/<uuid:workspace_id>/capability-proposals", CapabilityProposalListCreateView.as_view(), name="capability-proposal-list-create"),
    path("capability-proposals/<uuid:proposal_id>/decision", CapabilityProposalDecisionView.as_view(), name="capability-proposal-decision"),
    path("workspaces/<uuid:workspace_id>/memory-conflicts", MemoryConflictListCreateView.as_view(), name="memory-conflict-list-create"),
    path("memory-conflicts/<uuid:conflict_id>/resolve", MemoryConflictResolveView.as_view(), name="memory-conflict-resolve"),
    path("agent-teams/<uuid:team_id>/consensus", ConsensusSessionListCreateView.as_view(), name="consensus-session-list-create"),
    path("consensus-sessions/<uuid:session_id>", ConsensusSessionDetailView.as_view(), name="consensus-session-detail"),
    path("voice-sessions", VoiceSessionListCreateView.as_view(), name="voice-session-list-create"),
    path("voice-sessions/<uuid:session_id>", VoiceSessionDetailView.as_view(), name="voice-session-detail"),
    path("voice-sessions/<uuid:session_id>/turns", VoiceTurnCreateView.as_view(), name="voice-turn-create"),
]
