# Generated by Django 6.0.7 on 2026-07-12 22:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mfa_secret',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('deployment_mode', models.CharField(choices=[('deepseek_cloud', 'DeepSeek Cloud'), ('deepseek_self_hosted', 'DeepSeek Self-Hosted')], max_length=30)),
                ('encrypted_key', models.BinaryField(blank=True, null=True)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('label', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_credentials', to='core.workspace')),
            ],
            options={
                'db_table': 'provider_credentials',
            },
        ),
    ]
