# Generated by Django 6.0.7 on 2026-07-13 13:34

import core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_mfa_secret_providercredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('risk_classification', models.CharField(choices=[('safe', 'Safe'), ('sensitive', 'Sensitive'), ('dangerous', 'Dangerous')], max_length=20)),
                ('input_schema', models.JSONField(blank=True, default=dict)),
                ('output_schema', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(choices=[('built_in', 'Built-in'), ('skill_bundled', 'Skill-bundled'), ('integration', 'Integration')], default='built_in', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tools',
            },
        ),
        migrations.CreateModel(
            name='Coworker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('user', 'User'), ('team', 'Team'), ('organization', 'Organization')], default='user', max_length=20)),
                ('owner_id', models.UUIDField()),
                ('name', models.CharField(max_length=255)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworkers', to='core.workspace')),
            ],
            options={
                'db_table': 'coworkers',
            },
        ),
        migrations.CreateModel(
            name='CoworkerVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('role_description', models.TextField()),
                ('model_binding', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changelog', models.TextField(blank=True, null=True)),
                ('coworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.coworker')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coworker_versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.AddField(
            model_name='coworker',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.coworkerversion'),
        ),
        migrations.CreateModel(
            name='PermissionProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('default_tool_risk_policy', models.JSONField(default=core.models._default_risk_policy)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(blank=True, help_text='Null = platform default profile, per DATABASE.md §2.3.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_profiles', to='core.workspace')),
            ],
            options={
                'db_table': 'permission_profiles',
            },
        ),
        migrations.AddField(
            model_name='coworkerversion',
            name='permission_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coworker_versions', to='core.permissionprofile'),
        ),
        migrations.CreateModel(
            name='CoworkerToolAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_attachments', to='core.coworker')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworker_attachments', to='core.tool')),
            ],
            options={
                'db_table': 'coworker_tool_attachments',
            },
        ),
        migrations.AddConstraint(
            model_name='coworkerversion',
            constraint=models.UniqueConstraint(fields=('coworker', 'version_number'), name='uniq_coworker_version_number'),
        ),
        migrations.AddConstraint(
            model_name='coworkertoolattachment',
            constraint=models.UniqueConstraint(fields=('coworker', 'tool'), name='uniq_coworker_tool'),
        ),
    ]
