# Generated by Django 6.0.7 on 2026-07-13 18:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_seed_builtin_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('task_id', models.UUIDField(blank=True, null=True)),
                ('workflow_run_step_id', models.UUIDField(blank=True, null=True)),
                ('conversation_id', models.UUIDField(blank=True, null=True)),
                ('message_id', models.UUIDField(blank=True, null=True)),
                ('requested_action', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.coworker')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_requests', to='core.tool')),
            ],
            options={
                'db_table': 'approval_requests',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(choices=[('user', 'User'), ('coworker', 'Coworker'), ('system', 'System')], max_length=20)),
                ('actor_id', models.UUIDField(blank=True, null=True)),
                ('action', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=255)),
                ('resource_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.workspace')),
            ],
            options={
                'db_table': 'audit_log',
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='audit_log_workspa_dec503_idx')],
            },
        ),
    ]
