# Generated by Django 6.0.7 on 2026-07-13 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_approvalrequest_auditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.workspace'),
        ),
    ]
