# Generated by Django 6.0.7 on 2026-07-14 10:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_complete_builtin_tool_schemas'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('triggered_by', models.CharField(choices=[('user', 'User'), ('schedule', 'Schedule'), ('event', 'Event')], max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('needs_approval', 'Needs approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', max_length=20)),
                ('current_step_index', models.PositiveIntegerField(default=0)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'workflow_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentTeam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('collaboration_pattern', models.CharField(choices=[('sequential', 'Sequential'), ('manager_delegate', 'Manager/delegate'), ('parallel_merge', 'Parallel/merge')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_teams', to='core.workspace')),
            ],
            options={
                'db_table': 'agent_teams',
            },
        ),
        migrations.CreateModel(
            name='AgentTeamVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.agentteam')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'agent_team_versions',
            },
        ),
        migrations.CreateModel(
            name='AgentTeamRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('objective', models.TextField()),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('result', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='core.agentteam')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='core.agentteamversion')),
            ],
            options={
                'db_table': 'agent_team_runs',
            },
        ),
        migrations.CreateModel(
            name='AgentTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('researcher', 'Researcher'), ('writer', 'Writer'), ('reviewer', 'Reviewer'), ('developer', 'Developer'), ('tester', 'Tester'), ('security_reviewer', 'Security reviewer'), ('architect', 'Architect'), ('planner', 'Planner'), ('product_manager', 'Product manager'), ('custom', 'Custom')], max_length=30)),
                ('custom_role_label', models.CharField(blank=True, max_length=100)),
                ('position', models.PositiveIntegerField(default=0)),
                ('coworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_team_memberships', to='core.coworker')),
                ('agent_team_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.agentteamversion')),
            ],
            options={
                'db_table': 'agent_team_members',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='agentteam',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.agentteamversion'),
        ),
        migrations.CreateModel(
            name='ApiToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('token_prefix', models.CharField(max_length=20)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('scopes', models.JSONField(default=list)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_tokens', to='core.workspace')),
            ],
            options={
                'db_table': 'api_tokens',
            },
        ),
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('email', 'Email'), ('calendar', 'Calendar'), ('slack', 'Slack'), ('discord', 'Discord'), ('github', 'GitHub'), ('webhook', 'Generic webhook')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('encrypted_secret', models.BinaryField(blank=True, null=True)),
                ('workspace_token', models.CharField(max_length=128, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='core.workspace')),
            ],
            options={
                'db_table': 'integrations',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('listing_type', models.CharField(choices=[('skill', 'Skill'), ('capability_pack', 'Capability pack'), ('workflow_template', 'Workflow template'), ('tool', 'Tool')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('org_private', 'Organization private')], default='public', max_length=20)),
                ('pricing_model', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('pay_what_you_want', 'Pay what you want')], default='free', max_length=30)),
                ('price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('verified_publisher', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publisher_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_listings', to='core.workspace')),
            ],
            options={
                'db_table': 'marketplace_listings',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceListingVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version_string', models.CharField(max_length=50)),
                ('manifest', models.JSONField(default=dict)),
                ('changelog', models.TextField(blank=True)),
                ('review_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.marketplacelisting')),
            ],
            options={
                'db_table': 'marketplace_listing_versions',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceInstall',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('installed_at', models.DateTimeField(auto_now_add=True)),
                ('installed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_installs', to='core.workspace')),
                ('forked_from_listing_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='core.marketplacelistingversion')),
                ('listing_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installs', to='core.marketplacelistingversion')),
            ],
            options={
                'db_table': 'marketplace_installs',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField()),
                ('review_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.marketplacelisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_reviews', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_reviews', to='core.workspace')),
            ],
            options={
                'db_table': 'marketplace_reviews',
            },
        ),
        migrations.CreateModel(
            name='OrgPolicyFloor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('tool_risk_classification', models.CharField(choices=[('safe', 'Safe'), ('sensitive', 'Sensitive'), ('dangerous', 'Dangerous')], max_length=20)),
                ('min_required_policy', models.CharField(default='approval', max_length=20)),
                ('enforced', models.BooleanField(default=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_floors', to='core.workspace')),
            ],
            options={
                'db_table': 'org_policy_floors',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.workspace')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(max_length=30)),
                ('resource_id', models.UUIDField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='core.project')),
            ],
            options={
                'db_table': 'project_resources',
            },
        ),
        migrations.CreateModel(
            name='SkillVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('instruction_content', models.TextField()),
                ('declared_tools', models.JSONField(default=list)),
                ('dependencies', models.JSONField(default=list)),
                ('listing_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='core.marketplacelistingversion')),
            ],
            options={
                'db_table': 'skill_versions',
            },
        ),
        migrations.CreateModel(
            name='CoworkerSkillAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=True)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('coworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_attachments', to='core.coworker')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coworker_attachments', to='core.skillversion')),
            ],
            options={
                'db_table': 'coworker_skill_attachments',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('plan_tier', models.CharField(choices=[('self_hosted_free', 'Self-hosted (free)'), ('cloud_free', 'Cloud (free)'), ('cloud_pro', 'Cloud (pro)'), ('cloud_enterprise', 'Cloud (enterprise)')], max_length=20)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('past_due', 'Past due'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('renews_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='core.workspace')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_teams', to='core.workspace')),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest')], max_length=20)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='human_team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('marketplace_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='core.marketplacelisting')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='core.workspace')),
            ],
            options={
                'db_table': 'workflows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowRunStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('step_index', models.PositiveIntegerField()),
                ('step_type', models.CharField(choices=[('coworker_action', 'Coworker action'), ('tool_call', 'Tool call'), ('human_checkpoint', 'Human checkpoint')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('needs_approval', 'Needs approval'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('definition', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.workflowrun')),
            ],
            options={
                'db_table': 'workflow_run_steps',
                'ordering': ['step_index'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowTrigger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled'), ('event', 'Event')], max_length=20)),
                ('schedule_cron', models.CharField(blank=True, max_length=100, null=True)),
                ('event_source', models.CharField(blank=True, max_length=100, null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='core.workflow')),
            ],
            options={
                'db_table': 'workflow_triggers',
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('definition', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.workflow')),
            ],
            options={
                'db_table': 'workflow_versions',
            },
        ),
        migrations.AddField(
            model_name='workflowrun',
            name='workflow_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='core.workflowversion'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.workflowversion'),
        ),
        migrations.AddConstraint(
            model_name='agentteamversion',
            constraint=models.UniqueConstraint(fields=('agent_team', 'version_number'), name='uniq_agent_team_version'),
        ),
        migrations.AddConstraint(
            model_name='agentteammember',
            constraint=models.UniqueConstraint(fields=('agent_team_version', 'coworker'), name='uniq_agent_team_member'),
        ),
        migrations.AddConstraint(
            model_name='marketplacelistingversion',
            constraint=models.UniqueConstraint(fields=('listing', 'version_string'), name='uniq_listing_version'),
        ),
        migrations.AddConstraint(
            model_name='marketplaceinstall',
            constraint=models.UniqueConstraint(fields=('workspace', 'listing_version'), name='uniq_marketplace_install'),
        ),
        migrations.AddConstraint(
            model_name='marketplacereview',
            constraint=models.UniqueConstraint(fields=('listing', 'workspace', 'user'), name='uniq_listing_review'),
        ),
        migrations.AddConstraint(
            model_name='orgpolicyfloor',
            constraint=models.UniqueConstraint(fields=('workspace', 'tool_risk_classification'), name='uniq_org_policy_floor'),
        ),
        migrations.AddConstraint(
            model_name='projectresource',
            constraint=models.UniqueConstraint(fields=('project', 'resource_type', 'resource_id'), name='uniq_project_resource'),
        ),
        migrations.AddConstraint(
            model_name='coworkerskillattachment',
            constraint=models.UniqueConstraint(fields=('coworker', 'skill'), name='uniq_coworker_skill'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('workspace', 'name'), name='uniq_team_name'),
        ),
        migrations.AddConstraint(
            model_name='teammember',
            constraint=models.UniqueConstraint(fields=('team', 'user'), name='uniq_team_member'),
        ),
        migrations.AddConstraint(
            model_name='workflowrunstep',
            constraint=models.UniqueConstraint(fields=('workflow_run', 'step_index'), name='uniq_workflow_run_step'),
        ),
        migrations.AddConstraint(
            model_name='workflowversion',
            constraint=models.UniqueConstraint(fields=('workflow', 'version_number'), name='uniq_workflow_version'),
        ),
    ]
