# Generated by Django 6.0.7 on 2026-07-14 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_seed_integration_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest'), ('security_admin', 'Security admin'), ('billing_admin', 'Billing admin'), ('developer_admin', 'Developer admin'), ('auditor', 'Auditor')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowrunstep',
            name='step_type',
            field=models.CharField(choices=[('coworker_action', 'Coworker action'), ('tool_call', 'Tool call'), ('human_checkpoint', 'Human checkpoint'), ('condition', 'Condition')], max_length=30),
        ),
        migrations.AlterField(
            model_name='workspacemember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('member', 'Member'), ('guest', 'Guest'), ('security_admin', 'Security admin'), ('billing_admin', 'Billing admin'), ('developer_admin', 'Developer admin'), ('auditor', 'Auditor')], max_length=20),
        ),
        migrations.CreateModel(
            name='Artifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('presentation', 'Presentation'), ('diagram', 'Diagram'), ('video_analysis', 'Video analysis'), ('coworker_bundle', 'Coworker bundle'), ('compliance', 'Compliance evidence')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('content', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to=settings.AUTH_USER_MODEL)),
                ('source_coworker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifacts', to='core.coworker')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.workspace')),
            ],
            options={
                'db_table': 'artifacts',
            },
        ),
        migrations.CreateModel(
            name='AuditAnomaly',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('anomaly_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('summary', models.TextField()),
                ('evidence', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_anomalies', to='core.workspace')),
            ],
            options={
                'db_table': 'audit_anomalies',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceExport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('export_type', models.CharField(choices=[('audit', 'Audit log'), ('access', 'Access review'), ('soc2', 'SOC 2 evidence'), ('full', 'Full evidence bundle')], max_length=20)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('evidence', models.JSONField(default=dict)),
                ('checksum', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_exports', to='core.workspace')),
            ],
            options={
                'db_table': 'compliance_exports',
            },
        ),
        migrations.CreateModel(
            name='EnterpriseSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('data_region', models.CharField(choices=[('us', 'United States'), ('eu', 'European Union'), ('uk', 'United Kingdom'), ('ca', 'Canada'), ('au', 'Australia'), ('self_hosted', 'Self-hosted')], default='self_hosted', max_length=20)),
                ('retention_days', models.PositiveIntegerField(default=30)),
                ('legal_hold', models.BooleanField(default=False)),
                ('support_tier', models.CharField(choices=[('community', 'Community'), ('standard', 'Standard'), ('premium', 'Premium'), ('dedicated', 'Dedicated')], default='community', max_length=20)),
                ('sla_uptime_percent', models.DecimalField(decimal_places=3, default=99.5, max_digits=5)),
                ('sla_response_minutes', models.PositiveIntegerField(default=1440)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_settings', to='core.workspace')),
            ],
            options={
                'db_table': 'enterprise_settings',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marketplace_orders', to=settings.AUTH_USER_MODEL)),
                ('listing_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.marketplacelistingversion')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_orders', to='core.workspace')),
            ],
            options={
                'db_table': 'marketplace_orders',
            },
        ),
        migrations.CreateModel(
            name='MarketplacePayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('gross_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_payout_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='core.marketplacelisting')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='core.marketplaceorder')),
                ('publisher_workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_payouts', to='core.workspace')),
            ],
            options={
                'db_table': 'marketplace_payouts',
            },
        ),
        migrations.CreateModel(
            name='MarketplaceSecurityReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('score', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('needs_review', 'Needs review'), ('failed', 'Failed')], max_length=20)),
                ('findings', models.JSONField(default=list)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('listing_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_review', to='core.marketplacelistingversion')),
            ],
            options={
                'db_table': 'marketplace_security_reviews',
            },
        ),
        migrations.CreateModel(
            name='OrganizationPolicyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('resource_type', models.CharField(max_length=100)),
                ('action', models.CharField(max_length=100)),
                ('conditions', models.JSONField(blank=True, default=dict)),
                ('effect', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('require_approval', 'Require approval')], max_length=30)),
                ('priority', models.IntegerField(default=100)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_rules', to='core.workspace')),
            ],
            options={
                'db_table': 'organization_policy_rules',
                'ordering': ['priority', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='external', max_length=50)),
                ('provider_account_id', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to='core.workspace')),
            ],
            options={
                'db_table': 'payout_accounts',
            },
        ),
        migrations.CreateModel(
            name='SCIMToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('token_prefix', models.CharField(max_length=20)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scim_tokens', to='core.workspace')),
            ],
            options={
                'db_table': 'scim_tokens',
            },
        ),
        migrations.CreateModel(
            name='SSOProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('protocol', models.CharField(choices=[('saml', 'SAML 2.0'), ('oidc', 'OpenID Connect')], max_length=10)),
                ('issuer', models.CharField(max_length=500)),
                ('sso_url', models.URLField()),
                ('entity_id', models.CharField(blank=True, max_length=500)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('encrypted_secret', models.BinaryField(blank=True, null=True)),
                ('email_domains', models.JSONField(default=list)),
                ('attribute_mapping', models.JSONField(blank=True, default=dict)),
                ('jit_provisioning', models.BooleanField(default=True)),
                ('enforce_sso', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sso_providers', to='core.workspace')),
            ],
            options={
                'db_table': 'sso_providers',
            },
        ),
    ]
