# Generated by Django 6.0.7 on 2026-07-14 12:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def seed_phase4_tool(apps, schema_editor):
    Tool = apps.get_model("core", "Tool")
    Tool.objects.update_or_create(
        name="propose_capability",
        defaults={
            "description": "Request a tool or installed skill that would close a capability gap. A human must approve before it is attached.",
            "risk_classification": "safe",
            "provider": "built_in",
            "input_schema": {
                "type": "object",
                "properties": {
                    "coworker_id": {"type": "string", "format": "uuid"},
                    "target_type": {"type": "string", "enum": ["tool", "skill"]},
                    "target_id": {"type": "string", "format": "uuid"},
                    "rationale": {"type": "string"},
                },
                "required": ["coworker_id", "target_type", "target_id", "rationale"],
            },
            "output_schema": {
                "type": "object",
                "properties": {
                    "proposal_id": {"type": "string", "format": "uuid"},
                    "status": {"type": "string"},
                },
            },
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_seed_multimodal_artifact_tools'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsensusSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('method', models.CharField(choices=[('majority', 'Majority'), ('unanimous', 'Unanimous'), ('confidence_weighted', 'Confidence weighted')], default='majority', max_length=30)),
                ('status', models.CharField(choices=[('collecting', 'Collecting'), ('decided', 'Decided'), ('deadlocked', 'Deadlocked')], default='collecting', max_length=20)),
                ('result_option', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensus_sessions', to='core.agentteam')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'consensus_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('conversation_id', models.UUIDField()),
                ('language', models.CharField(default='en-US', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('coworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to='core.coworker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_sessions', to='core.workspace')),
            ],
            options={
                'db_table': 'voice_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceTurn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('user_transcript', models.TextField()),
                ('assistant_transcript', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('needs_approval', 'Needs approval'), ('failed', 'Failed')], max_length=20)),
                ('approval_request_id', models.UUIDField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='core.voicesession')),
            ],
            options={
                'db_table': 'voice_turns',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('proposed_by_type', models.CharField(choices=[('coworker', 'Coworker'), ('user', 'User')], default='coworker', max_length=20)),
                ('target_type', models.CharField(choices=[('tool', 'Tool'), ('skill', 'Skill')], max_length=20)),
                ('target_id', models.UUIDField()),
                ('target_name', models.CharField(max_length=255)),
                ('rationale', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_proposals', to='core.coworker')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_capability_proposals', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_proposals', to='core.workspace')),
            ],
            options={
                'db_table': 'capability_proposals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['workspace', 'status'], name='capability__workspa_bfae31_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConsensusVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('option', models.CharField(max_length=255)),
                ('confidence', models.DecimalField(decimal_places=3, default=1, max_digits=4)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coworker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consensus_votes', to='core.coworker')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.consensussession')),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consensus_vote', to='core.task')),
            ],
            options={
                'db_table': 'consensus_votes',
                'constraints': [models.UniqueConstraint(fields=('session', 'coworker'), name='uniq_consensus_vote')],
            },
        ),
        migrations.CreateModel(
            name='MemoryConflict',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('left_memory_id', models.UUIDField()),
                ('right_memory_id', models.UUIDField()),
                ('subject', models.CharField(max_length=255)),
                ('left_content', models.TextField()),
                ('right_content', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('resolution_strategy', models.CharField(blank=True, choices=[('keep_left', 'Keep first memory'), ('keep_right', 'Keep second memory'), ('merge', 'Merge')], max_length=20)),
                ('resolved_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_memory_conflicts', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_conflicts', to='core.workspace')),
            ],
            options={
                'db_table': 'memory_conflicts',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('workspace', 'left_memory_id', 'right_memory_id'), name='uniq_memory_conflict_pair')],
            },
        ),
        migrations.RunPython(seed_phase4_tool, migrations.RunPython.noop),
    ]
