# Generated by Django 6.0.7 on 2026-07-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_update_deprecated_deepseek_model_bindings'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='rationale',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
