# Generated by Django 6.0.7 on 2026-07-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_seed_pack_declared_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coworker',
            name='avatar_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
