# Generated by Django 6.0.7 on 2026-07-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_coworker_avatar_textfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='kind',
            field=models.CharField(choices=[('email', 'Email'), ('calendar', 'Calendar'), ('slack', 'Slack'), ('discord', 'Discord'), ('github', 'GitHub'), ('twitter', 'Twitter / X'), ('webhook', 'Generic webhook')], max_length=20),
        ),
    ]
