# Generated by Django 6.0.7 on 2026-07-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_seed_research_suite_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_completed', 'Task completed'), ('approval_requested', 'Approval requested'), ('workflow_failed', 'Workflow failed'), ('research_completed', 'Research completed'), ('website_changed', 'Website changed'), ('monitor_failed', 'Website monitor failed'), ('mention', 'Mention'), ('billing', 'Billing')], max_length=30),
        ),
    ]
