# Generated by Django 6.0.7 on 2026-07-20 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_alter_notification_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramConnection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("telegram_user_id", models.BigIntegerField(unique=True)),
                ("private_chat_id", models.BigIntegerField(unique=True)),
                (
                    "username",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("display_name", models.CharField(blank=True, max_length=255)),
                ("enabled", models.BooleanField(default=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_confirmed_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_connection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "telegram_connections"},
        ),
        migrations.CreateModel(
            name="TelegramDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("external_message_id", models.CharField(blank=True, max_length=64)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deliveries",
                        to="core.telegramconnection",
                    ),
                ),
                (
                    "notification",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_delivery",
                        to="core.notification",
                    ),
                ),
            ],
            options={"db_table": "telegram_deliveries"},
        ),
        migrations.CreateModel(
            name="TelegramLinkSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_link_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_link_sessions",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "telegram_link_sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "expires_at"],
                        name="telegram_l_user_id_23f935_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TelegramNotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("task_completed", models.BooleanField(default=True)),
                ("research_completed", models.BooleanField(default=True)),
                ("website_changed", models.BooleanField(default=True)),
                ("approval_requested", models.BooleanField(default=True)),
                ("task_failed", models.BooleanField(default=True)),
                ("monitor_failed", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="telegram_notification_preferences",
                        to="core.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "telegram_notification_preferences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "workspace"),
                        name="uniq_telegram_preference_user_workspace",
                    )
                ],
            },
        ),
    ]
