# Generated by Django 6.0.7 on 2026-07-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_raise_free_plan_limits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task_completed', 'Task completed'), ('approval_requested', 'Approval requested'), ('input_requested', 'Input requested'), ('workflow_failed', 'Workflow failed'), ('research_completed', 'Research completed'), ('website_changed', 'Website changed'), ('monitor_failed', 'Website monitor failed'), ('mention', 'Mention'), ('billing', 'Billing')], max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In progress'), ('needs_approval', 'Needs approval'), ('needs_input', 'Needs input'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
